services:

  neo4j:
    image: neo4j
    container_name: neo4j_Ges
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
    networks:
      - backend

  redis_stack:
    image: redis/redis-stack
    container_name: redis_stack
    ports:
      - "6379:6379"
      - "8001:8001"
    depends_on:
      - neo4j
    networks:
      - backend

  app:
    image: edjovilellaca/proyectote-app
    container_name: proyectote-app
    ports:
      - "3000:3000"
    depends_on:
      - neo4j
      - redis_stack
    environment:
      - NEO4J_URL=neo4j://neo4j_Ges:7687
    volumes:
      - ./Proyectote2:/app
    networks:
      - backend
    command: npm start

networks:
  backend:
    driver: bridge