services:

  neo:
    image: neo4j:latest
    container_name: neo1
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./VolumenesNeo4j/neo_data:/data
    networks:
      - backend

  redis:
    image: redis/redis-stack:latest
    container_name: redis01
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./VolumenesRedis/redis_data:/data
    networks:
      - backend

  app:
    build: .
    container_name: node_app2
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - neo
    environment:
      - REDIS_URL=redis://redis01:6379
      - NEO4J_URL=neo4j://neo1:7687
      - NEO4J_AUTH=none
    volumes:
      - ./NODE_APP2:/app
    networks:
      - backend
    command: npm start
  
networks:
  backend:
    driver: bridge